### ISSUE TITLE
Review of Cloud-hosted version

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guide-openliberty-operator-intro#1]
**What you will learn:**
_You will install an operator into an OpenShift cluster and use them to deploy and scale a sample microservice._

- [x] The above statement either needs to be plural or not.

**Step 5:**
- [x] No code shown for build.yaml file in SN.

_Run the following command to view the ImageStream object:_
- [x] Maybe explain what a ImageStream object is as we request them to run a command to view it.
- [x] No code shown for deploy.yaml file in SN.

**Step 6:**
- [x] Tell user to hold down control and click on the link in the terminal to open it in a new tab.

**Comment by jamiecoleman92** [comment]
FYI @davidwyao @gkwan-ibm

**Comment by gkwan-ibm** [comment]
@jamiecoleman92 

The above issues were fixed. 

For 
> The above statement either needs to be plural or not.

The statement was removed because the SNL does not need users to install the OL operator.

For
> Maybe explain what a ImageStream object is as we request them to run a command to view it.

Below the build.yaml code, there is already some description for ImageStream as. 

> The ImageStream object provides an abstraction from the image in the image registry. This allows you to reference and tag the image. The image registry used is the integrated internal OpenShift Container Registry.

Do you need more explanation or add some explanation before the `oc get imagestreams` command?

**Comment by jamiecoleman92** [comment]
@gkwan-ibm I would add some more explanation before the command (or move some information) rather than add in additional information.

**Comment by jamiecoleman92** [comment]
One last thing is that the "STEP 4: RUN configure.sh" step of the build takes quite a long time on this cluster and I was wondering if we could remove that to speed things up? @gkwan-ibm

**Comment by gkwan-ibm** [comment]
@jamiecoleman92 
It is the best practice to RUN configure.sh. It speeds up the image start time. I recommend not to remove it.

**Comment by davidwyao** [comment]
@gkwan-ibm @jamiecoleman92 
`imagestream` command has been made more descriptive with PR https://github.com/OpenLiberty/draft-guide-openliberty-operator-intro/pull/2.

**Comment by jamiecoleman92** [comment]
Everything looks good to me. I am happy to now close this issue.
