### ISSUE TITLE
Feedback for Operator guide

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guide-openliberty-operator-intro#12]
# Kubernetes Operator Guide Feedback

## What you’ll learn

- I still think we should be demonstrating the deployment of the system and inventory service using operators as we do in the Kubernetes into guide and most of our other guides.

## Installing the Operator
- The 2nd, 3rd and 4th command do not work on Windows. I tried them on the Microsoft terminal, cmd and powershell. I had to use a Linux terminal (Git Bash) to continue.
## Deploying the system microservice to Kubernetes
- Do we not have a new docker image for OL running on Java 17? The text above says to run this command to get the latest image but Java 11 seems old to me now.
- When I run the “kubectl get OpenLibertyApplications” command my application does not become RECONCILED. Looking at the output of the next command “kubectl describe olapps/system” this is the output I get:
Name:         system
Namespace:    default
Labels:       app.kubernetes.io/part-of=system
              name=system
Annotations:  <none>
API Version:  apps.openliberty.io/v1beta2
Kind:         OpenLibertyApplication
Metadata:
  Creation Timestamp:  2022-02-18T14:58:12Z
  Finalizers:
    finalizer.openlibertyapplications.apps.openliberty.io
  Generation:  2
  Managed Fields:
    API Version:  apps.openliberty.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:name:
      f:spec:
        .:
        f:applicationImage:
        f:env:
          .:
          k:{"name":"WLP_LOGGING_MESSAGE_FORMAT"}:
            .:
            f:name:
            f:value:
          k:{"name":"WLP_LOGGING_MESSAGE_SOURCE"}:
            .:
            f:name:
            f:value:
        f:expose:
        f:service:
          .:
          f:port:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-02-18T14:58:12Z
    API Version:  apps.openliberty.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
    Manager:         manager
    Operation:       Update
    Time:            2022-02-18T14:58:18Z
  Resource Version:  68495
  UID:               5268c8de-6d9a-4f89-a8a9-2b72416d6553
Spec:
  Application Image:  system:1.0-SNAPSHOT
  Application Name:   system
  Env:
    Name:       WLP_LOGGING_MESSAGE_FORMAT
    Value:      json
    Name:       WLP_LOGGING_MESSAGE_SOURCE
    Value:      message,trace,accessLog,ffdc,audit
  Expose:       true
  Pull Policy:  IfNotPresent
  Resources:
  Service:
    Port:  9080
    Type:  ClusterIP
Status:
  Conditions:
    Last Transition Time:  2022-02-18T14:58:13Z
    Message:               Ingress.extensions "system" is invalid: spec.rules[0].http.paths[0].pathType: Unsupported value: "": supported values: "Exact", "ImplementationSpecific", "Prefix"
    Reason:                Invalid
    Status:                False
    Type:                  Reconciled
  Image Reference:         system:1.0-SNAPSHOT
Events:
  Type     Reason           Age                From                   Message
  ----     ------           ----               ----                   -------
  Warning  ProcessingError  85s                open-liberty-operator  Operation cannot be fulfilled on deployments.apps "system": the object has been modified; please apply your changes to the latest version and try again
Warning  ProcessingError  2s (x17 over 85s)  open-liberty-operator  Ingress.extensions "system" is invalid: spec.rules[0].http.paths[0].pathType: Unsupported value: "": supported values: "Exact", "ImplementationSpecific", "Prefix"

### I can not continue from here!

**Comment by gkwan-ibm** [comment]
close
- the guide was published on April 2022
