### ISSUE TITLE
ID review

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/guide-openliberty-operator-intro#21]
For the most part, guide looks good from an ID perspective. I'll open a PR for a few minor tweaks.

The main issue I see with it is that the "Specifying other parameters" section seems very vague. I think we should add just a little more information here to explain what this section demonstrates. I assume it is demonstrating that you can specify different parameters for the Operator to implement when it deploys your application. For example, you can configure application health checks. We should also provide a link to Checking the health of microservices on Kubernetes guide for more information. 

Lastly, it's not clear what to look for when you "visit the microservice" in this section, since the browser just shows unformatted config. How is this result different than the one ion the previous section? What might a user look for as confirmation that the Operator successfully implemented the health checks?

**Comment by gkwan-ibm** [comment]
At the "Specifying optional parameters" section,
- add instructions to run `kubectl describe pods` after `kubectl apply -f deploy.yaml`
   - cloud-hosted run `kubectl describe pods | grep health`   
- will see the following lines in the output
```
    Liveness:     http-get http://:9080/health/live delay=30s timeout=10s period=2s #success=1 #failure=12
    Readiness:    http-get http://:9080/health/ready delay=30s timeout=10s period=2s #success=1 #failure=12
    Startup:      http-get http://:9080/health/started delay=30s timeout=10s period=2s #success=1 #failure=12
```

**Comment by gkwan-ibm** [comment]
close
- the guide was updated as https://github.com/OpenLiberty/guide-openliberty-operator-intro/issues/21#issuecomment-1149104486
