### ISSUE TITLE
Feedback for local and SN versions

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guide-openliberty-operator-intro#4]
**Things to consider changing**

- I think we either need to change this guide to use just Kubernetes or create a new guide that focuses on OCP although we may have that covered already. 
- I would suggest deploying both the System and Inventory microservices like most of our other deployment guides. There may be extra considerations and things the user might want to know when deploying two microservices and having them talk to one another.
- If we are using OCP I think we might want to mention and possibly get the user to try out the Console
- If using OCP we should stay away from specific OCP concepts such as image streams. If a seperate Kube guide is to be created then I am okay with OCP specific concepts in this guide.

@gcharters & @yeekangc please also provide your opinions on the above and if we need to consider any more changes.

**Comment by yeekangc** [comment]
This is a guide to cover deployment to Kubernetes using Open Liberty Operator.  That should be the focus.  It should cover the recommended path to use OLO to deploy Java apps and microservices to Kube environment.

@gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- won't fix
