### ISSUE TITLE
Update the 'Run in cloud' instructions

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/guide-openliberty-operator-intro#52]
- [x] The last link in the following snippet is pointing to a specific version that'll be outdated with time. Update it point to the main doc's install instructions: https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1.adoc#operator-installation 

_"The Open Liberty Operator is already installed in this Skills Network environment. To learn how to install the Open Liberty Operator yourself, see the [Deploying microservices to OpenShift by using Kubernetes Operators](https://openliberty.io/guides/cloud-openshift-operator.html#installing-the-operators) guide or the [Open Liberty Operator documentation](https://github.com/OpenLiberty/open-liberty-operator/tree/main/deploy/releases/1.2.0#readme)."_

- [x] Remove references to v1beta2 (old API version)
```
API Version:  apps.openliberty.io/v1beta2
Kind:         OpenLibertyApplication
```

- [x] The last link in the following snippet is pointing to the doc for old version. Update it to the following: https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1.adoc#configuration

_"You can also use the Open Liberty Operator to implement optional parameters in your application deployment by specifying the associated CRDs in your deploy.yaml file. For example, you can configure the [Kubernetes liveness, readiness and startup probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). Visit the [Open Liberty Operator user guide](https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1beta2.adoc#configuration) to find all of the supported optional CRDs."_

fyi @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
